// =============================================================================
// Mock Candidate Database - High-Fidelity People Search Data
// Simulates results from Apollo.io / People Data Labs / Proxycurl
// =============================================================================

const { v4: uuidv4 } = require('uuid');

const CANDIDATES = [
  {
    id: uuidv4(),
    name: "Priya Sharma",
    email: "priya.sharma@outlook.com",
    phone: "+919876543210",
    title: "Senior Software Engineer",
    company: "Infosys",
    location: "Bangalore, India",
    experience_years: 6,
    skills: ["JavaScript", "React", "Node.js", "Python", "AWS", "Docker"],
    education: "B.Tech Computer Science, IIT Delhi",
    linkedin: "linkedin.com/in/priya-sharma-dev",
    source: "Apollo.io",
    salary_range: "₹18-25 LPA",
    notice_period: "60 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Rahul Verma",
    email: "rahul.verma@gmail.com",
    phone: "+919123456789",
    title: "Full Stack Developer",
    company: "TCS",
    location: "Hyderabad, India",
    experience_years: 4,
    skills: ["Java", "Spring Boot", "React", "PostgreSQL", "Kubernetes"],
    education: "M.Tech Software Engineering, IIIT Hyderabad",
    linkedin: "linkedin.com/in/rahul-verma-fullstack",
    source: "People Data Labs",
    salary_range: "₹12-18 LPA",
    notice_period: "30 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Ananya Patel",
    email: "ananya.patel@yahoo.com",
    phone: "+919234567891",
    title: "Product Manager",
    company: "Flipkart",
    location: "Mumbai, India",
    experience_years: 7,
    skills: ["Product Strategy", "Agile", "Data Analysis", "SQL", "Figma", "A/B Testing"],
    education: "MBA, IIM Ahmedabad",
    linkedin: "linkedin.com/in/ananya-patel-pm",
    source: "Proxycurl",
    salary_range: "₹25-35 LPA",
    notice_period: "90 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Vikram Singh",
    email: "vikram.singh@hotmail.com",
    phone: "+919345678901",
    title: "DevOps Engineer",
    company: "Wipro",
    location: "Pune, India",
    experience_years: 5,
    skills: ["AWS", "Terraform", "Docker", "Kubernetes", "CI/CD", "Jenkins", "Python"],
    education: "B.E. Information Technology, COEP",
    linkedin: "linkedin.com/in/vikram-singh-devops",
    source: "Apollo.io",
    salary_range: "₹15-22 LPA",
    notice_period: "45 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Sneha Reddy",
    email: "sneha.reddy@gmail.com",
    phone: "+919456789012",
    title: "Data Scientist",
    company: "Amazon",
    location: "Bangalore, India",
    experience_years: 3,
    skills: ["Python", "TensorFlow", "PyTorch", "SQL", "Spark", "ML", "NLP"],
    education: "M.S. Data Science, ISI Kolkata",
    linkedin: "linkedin.com/in/sneha-reddy-ds",
    source: "People Data Labs",
    salary_range: "₹20-28 LPA",
    notice_period: "60 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Arjun Nair",
    email: "arjun.nair@proton.me",
    phone: "+919567890123",
    title: "Frontend Engineer",
    company: "Razorpay",
    location: "Bangalore, India",
    experience_years: 4,
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "GraphQL", "Testing"],
    education: "B.Tech CSE, NIT Trichy",
    linkedin: "linkedin.com/in/arjun-nair-frontend",
    source: "Proxycurl",
    salary_range: "₹14-20 LPA",
    notice_period: "30 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Deepika Iyer",
    email: "deepika.iyer@gmail.com",
    phone: "+919678901234",
    title: "Backend Engineer",
    company: "Swiggy",
    location: "Chennai, India",
    experience_years: 5,
    skills: ["Go", "Python", "gRPC", "Redis", "MongoDB", "Microservices", "Kafka"],
    education: "B.Tech IT, Anna University",
    linkedin: "linkedin.com/in/deepika-iyer-backend",
    source: "Apollo.io",
    salary_range: "₹16-24 LPA",
    notice_period: "60 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Karthik Menon",
    email: "karthik.menon@outlook.com",
    phone: "+919789012345",
    title: "Engineering Manager",
    company: "Google",
    location: "Hyderabad, India",
    experience_years: 10,
    skills: ["System Design", "Java", "Python", "Leadership", "Distributed Systems", "Cloud Architecture"],
    education: "M.Tech CSE, IIT Bombay",
    linkedin: "linkedin.com/in/karthik-menon-em",
    source: "People Data Labs",
    salary_range: "₹45-60 LPA",
    notice_period: "90 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Ritu Agarwal",
    email: "ritu.agarwal@gmail.com",
    phone: "+919890123456",
    title: "QA Automation Lead",
    company: "Microsoft",
    location: "Noida, India",
    experience_years: 6,
    skills: ["Selenium", "Cypress", "Jest", "Python", "CI/CD", "API Testing", "Performance Testing"],
    education: "B.Tech ECE, DTU",
    linkedin: "linkedin.com/in/ritu-agarwal-qa",
    source: "Proxycurl",
    salary_range: "₹18-25 LPA",
    notice_period: "60 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Aditya Joshi",
    email: "aditya.joshi@yahoo.com",
    phone: "+919901234567",
    title: "ML Engineer",
    company: "Flipkart",
    location: "Bangalore, India",
    experience_years: 4,
    skills: ["Python", "TensorFlow", "MLOps", "Kubernetes", "FastAPI", "Computer Vision"],
    education: "M.Tech AI, IIIT Bangalore",
    linkedin: "linkedin.com/in/aditya-joshi-ml",
    source: "Apollo.io",
    salary_range: "₹22-30 LPA",
    notice_period: "45 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Meera Krishnan",
    email: "meera.k@gmail.com",
    phone: "+919012345678",
    title: "UI/UX Designer",
    company: "CRED",
    location: "Bangalore, India",
    experience_years: 5,
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping", "Design Systems", "Interaction Design"],
    education: "B.Des, NID Ahmedabad",
    linkedin: "linkedin.com/in/meera-krishnan-ux",
    source: "People Data Labs",
    salary_range: "₹16-22 LPA",
    notice_period: "30 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Sanjay Gupta",
    email: "sanjay.gupta@outlook.com",
    phone: "+918901234567",
    title: "Cloud Architect",
    company: "Accenture",
    location: "Gurgaon, India",
    experience_years: 8,
    skills: ["AWS", "Azure", "GCP", "Terraform", "Serverless", "Security", "Cost Optimization"],
    education: "B.Tech CSE, BITS Pilani",
    linkedin: "linkedin.com/in/sanjay-gupta-cloud",
    source: "Proxycurl",
    salary_range: "₹30-42 LPA",
    notice_period: "90 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Nisha Bhatt",
    email: "nisha.bhatt@gmail.com",
    phone: "+918812345678",
    title: "Mobile Developer",
    company: "PhonePe",
    location: "Pune, India",
    experience_years: 4,
    skills: ["React Native", "Flutter", "Swift", "Kotlin", "Firebase", "REST APIs"],
    education: "B.Tech CSE, VIT Vellore",
    linkedin: "linkedin.com/in/nisha-bhatt-mobile",
    source: "Apollo.io",
    salary_range: "₹14-20 LPA",
    notice_period: "30 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Rohan Das",
    email: "rohan.das@proton.me",
    phone: "+918723456789",
    title: "Site Reliability Engineer",
    company: "Atlassian",
    location: "Bangalore, India",
    experience_years: 6,
    skills: ["Linux", "Kubernetes", "Prometheus", "Grafana", "Terraform", "Go", "Incident Management"],
    education: "M.Tech, IISC Bangalore",
    linkedin: "linkedin.com/in/rohan-das-sre",
    source: "People Data Labs",
    salary_range: "₹25-35 LPA",
    notice_period: "60 days",
    status: "active"
  },
  {
    id: uuidv4(),
    name: "Pooja Mishra",
    email: "pooja.mishra@gmail.com",
    phone: "+918634567890",
    title: "Technical Writer",
    company: "Freshworks",
    location: "Chennai, India",
    experience_years: 3,
    skills: ["Technical Documentation", "API Docs", "Markdown", "Git", "DITA", "Content Strategy"],
    education: "M.A. English Literature, JNU",
    linkedin: "linkedin.com/in/pooja-mishra-tw",
    source: "Proxycurl",
    salary_range: "₹8-14 LPA",
    notice_period: "30 days",
    status: "active"
  }
];

module.exports = { CANDIDATES };
